<a href="n_detail.htm" class="link1">
					<div class="n_tab_img img1" style="background-image:url({dede:global.cfg_templets_skin/}/imgs/news_1.png)"></div>
					<div class="n_tab_d1 det1 det">
						<date>[field:pubdate function="GetDateTimeMK(@me)"/]</date>
						<span>企业动态</span>
						<h3>[field:title/]</h3>
						<p>德洛德洛尼德洛尼德洛尼德洛尼德洛尼尼德洛尼德德洛尼德洛尼德洛尼尼德洛尼德洛尼德洛尼德洛尼德洛尼德洛尼德洛尼德洛尼德洛尼德洛尼</p>
					</div>
				</a>