<?php
$z[0]=Array("global","",301,333);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",443,475);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",564,596);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("include","",655,692);
$z[3][4]['filename']="header.htm";
$z[4]=Array("include","",1466,1508);
$z[4][4]['filename']="dln/sidebar.htm";
$z[5]=Array("include","",1552,1589);
$z[5][4]['filename']="footer.htm";

?>