<?php
$z[0]=Array("global","",304,336);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",446,478);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",567,599);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("include","",793,830);
$z[3][4]['filename']="header.htm";
$z[4]=Array("include","",7000,7042);
$z[4][4]['filename']="dln/sidebar.htm";
$z[5]=Array("include","",7086,7123);
$z[5][4]['filename']="footer.htm";

?>