<?php
$z[0]=Array("global","",257,289);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("channel","\r\n          	<li><a href='[field:typeurl/]' [field:rel/]><span>[field:typename/]</span></a></li>\r\n          		",391,552);
$z[1][4]['type']="top";
$z[1][4]['row']="10";
$z[1][4]['"']="";
$z[2]=Array("global","",649,676);
$z[2][4]['name']="cfg_powerby";
$z[3]=Array("global","",696,728);
$z[3][4]['name']="cfg_templets_skin";

?>