<?php
$z[0]=Array("global","",166,191);
$z[0][4]['name']="cfg_cmsurl";
$z[1]=Array("global","",257,282);
$z[1][4]['name']="cfg_cmsurl";
$z[2]=Array("global","",344,369);
$z[2][4]['name']="cfg_cmsurl";
$z[3]=Array("global","",402,428);
$z[3][4]['name']="cfg_dataurl";
$z[4]=Array("global","",556,583);
$z[4][4]['name']="cfg_basehost";
$z[5]=Array("global","",656,683);
$z[5][4]['name']="cfg_basehost";
$z[6]=Array("global","",686,712);
$z[6][4]['name']="cfg_webname";
$z[7]=Array("global","",865,892);
$z[7][4]['name']="cfg_basehost";
$z[8]=Array("global","",904,936);
$z[8][4]['name']="cfg_templets_skin";
$z[9]=Array("global","",983,1009);
$z[9][4]['name']="cfg_webname";
$z[10]=Array("mda","",1060,1089);
$z[10][4]['name']="468x60_SSP";
$z[11]=Array("global","",1402,1427);
$z[11][4]['name']="cfg_cmsurl";
$z[12]=Array("channel","\r\n          <li><a href='[field:typeurl/]' [field:rel/]><span>[field:typename/]</span></a></li>\r\n          ",1470,1743);
$z[12][4]['type']="top";
$z[12][4]['row']="10";
$z[12][4]['currentstyle']="<li class='hover'><a href='~typelink~' ~rel~><span>~typename~</span></a></li>";
$z[13]=Array("global","",1843,1868);
$z[13][4]['name']="cfg_cmsurl";
$z[14]=Array("tag","\r\n            <li><a href='[field:link/]'>[field:tag /]</a></li>\r\n            ",2688,2820);
$z[14][4]['row']="10";
$z[14][4]['getall']="1";
$z[14][4]['sort']="month";
$z[15]=Array("mda","",2977,3006);
$z[15][4]['name']="950x90_SSP";

?>