<?php
$z[0]=Array("global","",257,289);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",377,409);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",515,547);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("global","",632,664);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("global","",697,729);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",1078,1110);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("global","",1213,1245);
$z[6][4]['name']="cfg_templets_skin";
$z[7]=Array("global","",1246,1278);
$z[7][4]['name']="cfg_templets_skin";
$z[8]=Array("global","",1518,1550);
$z[8][4]['name']="cfg_templets_skin";
$z[9]=Array("global","",1909,1934);
$z[9][4]['name']="cfg_cmsurl";
$z[10]=Array("channel","\r\n          <li><a href='[field:typeurl/]' [field:rel/]>[field:typename/]</a></li>\r\n          ",1993,2240);
$z[10][4]['type']="top";
$z[10][4]['row']="10";
$z[10][4]['currentstyle']="<li class='hover'><a href='~typelink~' ~rel~>~typename~</a></li>";
$z[11]=Array("global","",2469,2501);
$z[11][4]['name']="cfg_templets_skin";

?>