<?php
$z[0]=Array("global","",303,335);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",445,477);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",566,598);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("include","",655,692);
$z[3][4]['filename']="header.htm";
$z[4]=Array("include","",3044,3086);
$z[4][4]['filename']="dln/sidebar.htm";
$z[5]=Array("include","",3130,3167);
$z[5][4]['filename']="footer.htm";

?>