<?php
$z[0]=Array("global","",342,374);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",484,516);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",605,637);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("include","",827,864);
$z[3][4]['filename']="header.htm";
$z[4]=Array("include","",5033,5075);
$z[4][4]['filename']="dln/sidebar.htm";
$z[5]=Array("include","",5119,5156);
$z[5][4]['filename']="footer.htm";

?>