<?php
$z[0]=Array("global","",318,350);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",460,492);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",581,613);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("include","",745,782);
$z[3][4]['filename']="header.htm";
$z[4]=Array("include","",2429,2471);
$z[4][4]['filename']="dln/sidebar.htm";
$z[5]=Array("include","",2515,2552);
$z[5][4]['filename']="footer.htm";

?>