<?php
$z[0]=Array("include","",392,429);
$z[0][4]['filename']="header.htm";
$z[1]=Array("global","",518,550);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("list","\r\n				<a href=\"[field:arcurl/]\"  title=\"[field:fulltitle/]\" class=\"link\">\r\n					<div class=\"n_tab_img\" style=\"background-image:url([field:picname /])\"></div>\r\n					<div class=\"n_tab_det\">\r\n						<date>[field:pubdate function=\"GetDateTimeMK(@me)\"/]</date>\r\n						<span>企业动态</span>\r\n						<h3>[field:fulltitle/]</h3>\r\n						<p>[field:newsdisc /]</p>\r\n					</div>\r\n				</a>\r\n            ",878,1306);
$z[2][4]['pagesize']="6";
$z[3]=Array("include","",1404,1442);
$z[3][4]['filename']="sidebar.htm";
$z[4]=Array("include","",1483,1520);
$z[4][4]['filename']="footer.htm";

?>