<?php
$z[0]=Array("global","",298,330);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",440,472);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("include","",728,765);
$z[2][4]['filename']="header.htm";
$z[3]=Array("list","\r\n				<div class=\"sh_tabs_d1 dets1\">\r\n					<h3>[field:title/]</h3>\r\n					<p>[field:pubdate function=\"GetDateTimeMK(@me)\"/]</p>\r\n					<span>400-733-0006/010-00000000</span>\r\n				</div>\r\n			",2011,2236);
$z[3][4]['pagesize']="20";
$z[4]=Array("include","",2326,2368);
$z[4][4]['filename']="dln/sidebar.htm";
$z[5]=Array("include","",2412,2449);
$z[5][4]['filename']="footer.htm";

?>